# Generated by Django 2.1.3 on 2018-12-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(default='', max_length=512)),
                ('category', models.CharField(default='Fun', max_length=64)),
                ('Info', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='gherbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, upload_to='')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
                ('XP', models.IntegerField(default=0)),
                ('accepted_challenges', models.ManyToManyField(to='main.Challenge')),
                ('follows', models.ManyToManyField(related_name='follower', to='main.User_profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gherbi',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_gherbi', to='main.User_profile'),
        ),
        migrations.AddField(
            model_name='gherbi',
            name='vote',
            field=models.ManyToManyField(related_name='voted_gherbi', to='main.User_profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_comment', to='main.User_profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_comment', to='main.User_profile'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User_profile'),
        ),
    ]
